feat(Models, Seeder, Factory) : Add Model, Seeder, Factory Kepegawaian
Waggish-Mepo/SIMAP-TU pull request #20
Opened 2022-02-25 06:00 UTC by Azrielfhr2

2022-02-25 07:03 UTC, suryomujahid requested changes

2022-02-25 07:03 UTC, suryomujahid commented on database/factories/EmployeeFactory.php
> +            'nama' => $nama,
id itu nanti dari userable_idnya model User
sama halnya nama

2022-02-25 07:03 UTC, suryomujahid commented on database/factories/EmployeeFactory.php
> +            'nama' => $nama,
dihapus aja yang ini

2022-02-25 07:03 UTC, suryomujahid commented on database/factories/EmployeeFactory.php
> +            'kk' => '',
ini yang nilainya kosong dihapus aja, kan udah nullable di tablenya

2022-02-25 07:03 UTC, suryomujahid commented on app/Models/Certificates.php
> +class Certificates extends Model
naming convention, untuk penamaan model itu singular. jadi nama filenya Certificate, terus classnya juga jadi Certificate

2022-02-25 07:03 UTC, suryomujahid commented on database/seeders/EmployeeSeeder.php
> +        EmployeeFactory::new()->count(5)->create();
ini ntar dibuat bareng UserFactory, biar ngambil id dan namanya dari sana

2022-02-25 10:02 UTC, Azrielfhr2 commented on database/factories/EmployeeFactory.php
> +            'nama' => $nama,
Okee okee

2022-02-25 10:03 UTC, Azrielfhr2 commented on database/factories/EmployeeFactory.php
> +            'kk' => '',
Wokee

2022-02-25 10:03 UTC, Azrielfhr2 commented on app/Models/Certificates.php
> +class Certificates extends Model
Okeee udahh

2022-02-25 10:03 UTC, Azrielfhr2 commented on database/seeders/EmployeeSeeder.php
> +        EmployeeFactory::new()->count(5)->create();
Oke, jadi file nya gw apus aja ya

2022-02-28 11:54 UTC, suryomujahid approved these changes
LGTM

2022-02-28 12:00 UTC, merged