feat(migration) : Add table guru
Waggish-Mepo/SIMAP-TU pull request #4
Opened 2022-02-11 13:42 UTC by Azrielfhr2

2022-02-12 02:51 UTC, suryomujahid requested changes

2022-02-12 02:51 UTC, suryomujahid commented on database/migrations/2022_02_11_135522_create_teachers.php
> +            $table->string('nama');
mungkin field yang ini bisa dihapus, karena nama udah ada di table users

2022-02-12 02:51 UTC, suryomujahid commented on database/migrations/2022_02_11_135522_create_teachers.php
> +            $table->string('nrg_sertifikasi');
ini pakai integer, nrg itu "Nomor Registrasi Guru"

2022-02-12 02:52 UTC, suryomujahid commented on database/migrations/2022_02_11_135522_create_teachers.php
> +            $table->string('nama');
field ini dihapus, karena nama udah ada di users

2022-02-12 02:53 UTC, suryomujahid commented on database/migrations/2022_02_11_135522_create_teachers.php
> +            $table->string('nama');
yang field nama doang ya

2022-02-12 02:53 UTC, suryomujahid commented on database/migrations/2022_02_11_135522_create_teachers.php
> +            $table->string('nrg_sertifikasi');
yang line 70

2022-02-12 03:09 UTC, Azrielfhr2 commented on database/migrations/2022_02_11_135522_create_teachers.php
> +            $table->string('nama');
field nama hapus?

2022-02-12 03:18 UTC, Azrielfhr2 commented on database/migrations/2022_02_11_135522_create_teachers.php
> +            $table->string('nama');
okee okee

2022-02-14 02:35 UTC, suryomujahid commented
lgtm

2022-02-14 02:35 UTC, merged