Feat Ijazah
Waggish-Mepo/SIMAP-TU pull request #40
Opened 2022-04-18 14:39 UTC by Azrielfhr2

Di lanjut di sekolah

2022-04-27 08:18 UTC, Saekyo commented on resources/views/employee_affair/modal/_edit_ijazah.blade.php
> +                            class="block mb-2 text-sm font-medium text-gray-900 dark:text-gray-300">Nins</label>
typo nins -> nisn

2022-04-27 08:20 UTC, Saekyo commented on resources/views/employee_affair/modal/_edit_ijazah.blade.php
> +                <button type="button" class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm p-1.5 ml-auto inline-flex items-center dark:hover:bg-gray-600 dark:h
ini 
`data-modal-toggle="modal-add-ijazah"`
jadi 
`data-modal-toggle="modal-edit-ijazah">`

2022-04-27 08:23 UTC, Saekyo commented
Kalo yang error modal gatau kenapa
Gw gabisa add ijazah
```
An invalid form control with name='nomor' is not focusable.
edit:1 An invalid form control with name='jurusan' is not focusable.
edit:1 An invalid form control with name='nama_sekolah' is not focusable.
edit:1 An invalid form control with name='npsn' is not focusable.
edit:1 An invalid form control with name='kabupaten_kota' is not focusable.
edit:1 An invalid form control with name='provinsi' is not focusable.
edit:1 An invalid form control with name='nama_ortu' is not focusable.
edit:1 An invalid form control with name='nis' is not focusable.
edit:1 An invalid form control with name='nisn' is not focusable.
edit:1 An invalid form control with name='no_peserta_un' is not focusable
```
Error di consolenya kaya gitu pas klik button submit di modalnya

2022-04-27 08:38 UTC, Azrielfhr2 commented on resources/views/employee_affair/modal/_edit_ijazah.blade.php
> +                <button type="button" class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm p-1.5 ml-auto inline-flex items-center dark:hover:bg-gray-600 dark:h
OKee okee makasih ki nanti malem gw fix

2022-04-27 14:27 UTC, Saekyo commented
LGTM

2022-05-02 01:06 UTC, suryomujahid requested changes
sedikit comment dari gw @Azrielfhr2

2022-05-02 01:06 UTC, suryomujahid commented on resources/views/employee_affair/employee/detail_ijazah.blade.php
> +    </script>
ini script untuk apa ya?

2022-05-02 01:06 UTC, suryomujahid commented on resources/views/employee_affair/employee/detail.blade.php
> +            console.log(updateRoute)
```suggestion

```

2022-05-02 01:06 UTC, suryomujahid commented on resources/views/employee_affair/employee/detail.blade.php
> +                    console.log(data);
```suggestion

```

2022-05-02 01:06 UTC, suryomujahid commented on database/migrations/2022_04_18_101812_create_ijazah_table.php
> +        });
ini udah ditentuin nullablenya yang mana aja?

2022-05-02 01:06 UTC, suryomujahid commented on app/Models/Ijazah.php
>      ];
kalau semisal required semua dihapus aja fillablenya

2022-05-02 06:03 UTC, Azrielfhr2 commented
Okee okee nanti gw cek, lagi kaga buka laptop. Lagi di luar

2022-05-02 11:01 UTC, Azrielfhr2 commented on database/migrations/2022_04_18_101812_create_ijazah_table.php
> +        });
Gak ada yang nullable deh kayanya, soalnya harus di isi semua

2022-05-02 14:45 UTC, suryomujahid commented
setelah diresolve itu sudah sambil testing kan @Azrielfhr2 ?

2022-05-03 22:03 UTC, Azrielfhr2 commented
> 

Udahhh di tes ko

2022-05-04 06:45 UTC, suryomujahid approved these changes
lgtm

2022-05-04 06:45 UTC, merged