feat(user): Add User model, factory & seeder
Waggish-Mepo/SIMAP-TU pull request #8
Opened 2022-02-17 04:06 UTC by Saekyo

2022-02-17 04:25 UTC, Azrielfhr2 commented on app/Models/User.php
> +        'id',
ini id nya fillable?

2022-02-17 08:57 UTC, suryomujahid commented on app/Models/User.php
> +
```suggestion
    protected $hidden = [
        'password',
        'remember_token',
    ];
```

2022-02-17 09:00 UTC, suryomujahid requested changes
btw, next kalau ngepush. file app.css dari public/css gak usah diinclude ya ki

2022-02-17 09:31 UTC, Saekyo commented on app/Models/User.php
> +        'id',
Entah, masih bingung ini

2022-02-17 11:00 UTC, suryomujahid approved these changes
lgtm

2022-02-18 02:19 UTC, Azrielfhr2 commented
LGTM👌

2022-02-18 03:49 UTC, merged